### ISSUE TITLE
Software improvements

### ISSUE THREAD

**Issue by leochan2009** [leochan2009/ProstateCryoAblation#3]
- [x] Don’t switch the view when the “add” button is clicked.

- [x] Iceball/needle models are not updated when a needle is added / deleted.

- [x] IceRod vs IceSeed, add probe setting in the target table.

- [x] Disable the masking when entering the segmentation widget

- [x] ScreenShot, replace the windowlevel button with screenshot button

- [x] Able to place targets at any series

- [x] Long series name makes the GUI extended

- [x] Distance among any two needles

**Comment by leochan2009** [comment]
global setting of the probe type is now available. however, during the case, the Dr could use different probes for different targets. Still need discuss with clinicians about the best UI.  @tokjun

**Comment by tokjun** [comment]
I think it should be integrated into the table showing the list of probes.
